### ISSUE TITLE
Installed Plugin status: "Malfunctioned"

### ISSUE THREAD

**Issue by Hydranet** [jellyfin/jellyfin-plugin-tmdb#12]
I followed the instructions to build the plugin:
1. Cloned it to a directory
2. Built it by running: dotnet publish --configuration Release --output TheMovieDb
3. I moved the output directory to /var/lib/jellyfin/plugins, change the permissions to the jellyfin user and ran a restorecon for selinux
4. I restarted jellyfin
5. When I go to "Plugins" in the JellyFin interface it says that the plugin has the status: "Malfunctioned"

These are the versions I think you need:
OS: RHEL8 clone x86_64
Dotnet: 5.0
Jellyfin-Server: 10.7.5-1

I checked the Jellyfin server log file looking for ERR lines about "TheMovieDb".
[jellyfin-plugin-tmdb.log](https://github.com/jellyfin/jellyfin-plugin-tmdb/files/6572168/jellyfin-plugin-tmdb.log)
There I see the same error several times: "**Unknown exception was thrown. Disabling plugin**.", it tries to load a dll
for win-x86, win-arm64, win-arm and win-x64. I don't understand why it doesn't see why it doesn't see the plugin 
on my CentOS install because the library is there:
`-rwxrw-r--. 1 jellyfin jellyfin 1156552 Aug 28  2020 TheMovieDB/runtimes/linux-x64/native/libe_sqlite3.so`

Am I missing something or what is going wrong?

**Comment by crobibero** [comment]
This plugin is still bundled with the core server so it can’t yet be added as a plugin.
